In [2]:
import torch

ckpt1 = torch.load('../logs_ensemble/train_mlp_single_label_NC_deeper_esm1b_no_early_stop_2024_04_05__13_15_14/checkpoints/checkpoints_1800.pt')
ckpt2 = torch.load('../logs_ensemble/train_mlp_single_label_NC_deeper_esm1b_no_early_stop_2024_04_05__13_15_14/checkpoints/checkpoints_1900.pt')
ckpt1

OrderedDict([('layers.0.0.weight',
              tensor([[-2.1823e-05,  1.4919e-02, -2.2752e-02,  ...,  1.3140e-02,
                        1.8287e-02,  1.8770e-02],
                      [-2.6907e-02, -7.2880e-02, -1.0946e-02,  ..., -1.5267e-03,
                        4.5335e-02, -8.0391e-02],
                      [-1.8364e-02, -1.9454e-02,  1.8565e-02,  ...,  9.5119e-04,
                       -1.5693e-02, -5.8687e-03],
                      ...,
                      [-2.5239e-02,  3.2746e-02,  2.0951e-02,  ...,  6.6215e-02,
                       -2.1166e-05, -7.2105e-02],
                      [-8.0811e-02, -6.1508e-03, -2.7563e-02,  ...,  7.8793e-02,
                        3.6648e-02, -2.7310e-02],
                      [ 9.5255e-02,  5.0914e-02,  2.0693e-02,  ..., -7.2970e-02,
                       -8.8989e-02, -7.2880e-02]], device='cuda:3')),
             ('layers.0.0.bias',
              tensor([-0.0042, -0.0313, -0.0178,  ..., -0.0119, -0.0508, -0.0255],
                

In [3]:
ckpt2

OrderedDict([('layers.0.0.weight',
              tensor([[-2.1823e-05,  1.4919e-02, -2.2752e-02,  ...,  1.3140e-02,
                        1.8287e-02,  1.8770e-02],
                      [-2.5182e-02, -6.9676e-02, -1.0592e-02,  ..., -7.9985e-03,
                        4.3924e-02, -8.1913e-02],
                      [-1.8364e-02, -1.9454e-02,  1.8565e-02,  ...,  9.5119e-04,
                       -1.5693e-02, -5.8687e-03],
                      ...,
                      [-2.1211e-02,  3.4128e-02,  2.7297e-02,  ...,  6.6068e-02,
                       -1.1414e-03, -6.8766e-02],
                      [-8.1506e-02, -4.5451e-03, -2.8546e-02,  ...,  7.6343e-02,
                        3.1085e-02, -3.2258e-02],
                      [ 8.6948e-02,  5.1129e-02,  3.6023e-03,  ..., -7.2285e-02,
                       -8.7927e-02, -7.9343e-02]], device='cuda:3')),
             ('layers.0.0.bias',
              tensor([-0.0042, -0.0311, -0.0178,  ..., -0.0113, -0.0495, -0.0268],
                

In [2]:
import torch

means = torch.load('../logs_debug/train_mlp_single_label_NC_deeper_esm1b_2024_03_30__11_24_38_NC_v2_cosine_bs1000/checkpoints/means.pt')
means, type(means), means.shape

(tensor([[ 0.1619, -1.4601,  1.8481,  ..., -1.0913,  1.1436,  0.3131],
         [-0.8649, -0.7610, -1.1271,  ...,  0.3165, -0.3913,  0.2218],
         [ 1.1067, -0.8318,  0.6679,  ..., -1.3296,  1.0651, -1.1601],
         ...,
         [ 1.5419, -0.3566,  0.8146,  ...,  0.8079,  0.1242, -0.7519],
         [-0.2647,  0.6124, -2.0240,  ..., -0.9149, -1.0613,  0.0082],
         [-0.3950,  0.1507, -0.6655,  ..., -0.3974, -0.8287,  0.6824]]),
 torch.Tensor,
 torch.Size([1920, 2000]))